import type { ServiceSpec } from '@vis/core';
import { telemetryDependencies, telemetryDevDependencies } from './telemetry-files';

export function renderPackageJson(
  spec: ServiceSpec,
  packageName: string,
  packageVersion: string
): string {
  return JSON.stringify(
    {
      name: packageName,
      version: packageVersion,
      description: `MCP server for ${spec.title}`,
      type: 'module',
      main: './dist/index.js',
      scripts: {
        build: 'tsc',
        start: 'node dist/index.js',
        dev: 'tsc --watch',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.0.0',
        cors: '^2.8.5',
        dotenv: '^16.4.5',
        'node-fetch': '^3.3.2',
        zod: '^3.22.0',
        'zod-to-json-schema': '^3.22.0',
        ...telemetryDependencies(),
      },
      devDependencies: {
        '@types/cors': '^2.8.17',
        '@types/node': '^20.0.0',
        typescript: '^5.4.0',
        ...telemetryDevDependencies(),
      },
      engines: {
        node: '>=18.0.0',
      },
    },
    null,
    2
  );
}

export function renderTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'Node16',
        moduleResolution: 'Node16',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: true,
      },
      include: ['src'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2
  );
}

export function renderHttpClient(): string {
  return `
import fetch from "node-fetch";
import { BASE_URL } from "./config.js";

export interface ApiCallOptions {
  method: string;
  url: string;
  params?: Record<string, string>;
  headers?: Record<string, string>;
  body?: unknown;
}

export async function callApi(options: ApiCallOptions): Promise<unknown> {
  const { method, params = {}, headers = {}, body } = options;

  // Build URL with query parameters
  let url = options.url;
  const queryString = new URLSearchParams(
    Object.entries(params).filter(([, v]) => v !== undefined && v !== "")
  ).toString();
  if (queryString) url += \`?\${queryString}\`;

  const fetchOptions: Parameters<typeof fetch>[1] = {
    method,
    headers,
  };

  if (body !== undefined && method !== "GET" && method !== "HEAD") {
    fetchOptions.body = JSON.stringify(body);
  }

  const response = await fetch(url, fetchOptions);

  const contentType = response.headers.get("content-type") ?? "";
  const responseText = await response.text();

  if (!response.ok) {
    throw new Error(
      \`HTTP \${response.status} \${response.statusText}: \${responseText}\`
    );
  }

  if (contentType.includes("application/json")) {
    try {
      return JSON.parse(responseText);
    } catch {
      return responseText;
    }
  }

  return responseText;
}
`.trimStart();
}

export function renderTypes(): string {
  return `
import type { z } from "zod";

/** Contract for a single MCP tool backed by one API operation */
export interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: z.ZodObject<z.ZodRawShape>;
  execute(args: unknown): Promise<unknown>;
}
`.trimStart();
}

export function renderConfig(spec: ServiceSpec): string {
  return `
/**
 * Runtime configuration for the generated MCP server.
 *
 *   MCP_BASE_URL      Override the upstream API base URL.
 *
 *   MCP_TRANSPORT     "stdio" (default, for Claude Desktop) | "sse" | "http"
 *   PORT              HTTP server port when using sse/http transport. Default 3000.
 *
 *   TELEMETRY_ENABLED   "true" to enable all telemetry. Default false.
 *   NODE_ENV            "development" | "staging" | "production". Default "development".
 *
 *   METRICS_ENABLED   "false" to disable. Default true (when TELEMETRY_ENABLED).
 *   METRICS_PORT      Prometheus scrape port. Default 9090.
 *   METRICS_PREFIX    Metric name prefix. Default "mcp".
 *
 *   LOGS_ENABLED      "false" to disable. Default true (when TELEMETRY_ENABLED).
 *   LOG_LEVEL         "debug" | "info" | "warn" | "error". Default "info".
 *   LOKI_URL          Loki push URL, e.g. "http://loki:3100". Omit → console only.
 *   LOKI_BATCH_MS     Log batch flush interval in ms. Default 5000.
 *
 *   TRACES_ENABLED      "true" to enable. Default false.
 *   OTLP_ENDPOINT       Tempo OTLP/HTTP base URL, e.g. "http://tempo:4318". Default that.
 *   TRACE_SAMPLE_RATE   0.0–1.0. Default 0.1 (10 %).
 *
 *   When auth is implemented, add MCP_API_KEY / MCP_BEARER_TOKEN env vars here
 *   and inject them in src/http-client.ts. ServiceSpec.securitySchemes carries
 *   the upstream auth metadata.
 */
export const BASE_URL: string =
  process.env["MCP_BASE_URL"] ?? ${JSON.stringify(spec.baseUrl)};
`.trimStart();
}

export function renderReadme(spec: ServiceSpec, operations: number): string {
  return `
# ${spec.title} MCP Server

Auto-generated by **vis** from OpenAPI ${spec.version}.

${spec.description ? `${spec.description}\n` : ''}
## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

## Usage

\`\`\`bash
node dist/index.js
\`\`\`

The server communicates over **stdio** (MCP standard transport).

## Configuration

| Variable | Default | Purpose |
|---|---|---|
| \`MCP_BASE_URL\` | \`${spec.baseUrl}\` | Upstream API base URL |
| \`MCP_TRANSPORT\` | \`stdio\` | Transport: \`stdio\` · \`sse\` · \`http\` |
| \`PORT\` | \`3000\` | HTTP port (sse/http transport only) |
| **Telemetry** | | |
| \`TELEMETRY_ENABLED\` | \`false\` | Master switch for all telemetry |
| \`NODE_ENV\` | \`development\` | \`development\` · \`staging\` · \`production\` |
| **Prometheus** | | |
| \`METRICS_ENABLED\` | \`true\` | Expose \`/metrics\` on a dedicated port |
| \`METRICS_PORT\` | \`9090\` | Prometheus scrape port |
| \`METRICS_PREFIX\` | \`mcp\` | Prefix for all metric names |
| **Loki** | | |
| \`LOGS_ENABLED\` | \`true\` | Enable structured logging |
| \`LOG_LEVEL\` | \`info\` | \`debug\` · \`info\` · \`warn\` · \`error\` |
| \`LOKI_URL\` | _(console only)_ | Loki push URL e.g. \`http://loki:3100\` |
| \`LOKI_BATCH_MS\` | \`5000\` | Log batch flush interval (ms) |
| **Tempo** | | |
| \`TRACES_ENABLED\` | \`false\` | Enable distributed tracing |
| \`OTLP_ENDPOINT\` | \`http://tempo:4318\` | Tempo OTLP/HTTP base URL |
| \`TRACE_SAMPLE_RATE\` | \`0.1\` | Sampling rate 0.0–1.0 |

## Tools (${operations} total)

${spec.operations
  .map(
    (op) =>
      `### \`${op.operationId}\`\n\`${op.method.toUpperCase()} ${op.path}\`${op.summary ? `\n\n${op.summary}` : ''}`
  )
  .join('\n\n')}

## Extension Points

The following capabilities are **IR-supported but not yet implemented** in the generated output:

- **Authentication**: \`ServiceSpec.securitySchemes\` carries upstream auth metadata. Inject headers in \`src/http-client.ts\` and \`MCP_API_KEY\` / \`MCP_BEARER_TOKEN\` env vars in \`src/config.ts\`.
- **SSE transport**: Replace \`StdioServerTransport\` with the SDK's SSE transport. The \`TransportKind\` field in the IR already models this.
- **HTTP transport**: Same swap point as SSE; the IR \`transport\` field is \`"http"\`-ready.
`.trimStart();
}
