import type { ServiceSpec } from '@vis/core';

export function renderPackageJson(
  spec: ServiceSpec,
  packageName: string,
  packageVersion: string
): string {
  return JSON.stringify(
    {
      name: packageName,
      version: packageVersion,
      description: `MCP server for ${spec.title}`,
      type: 'module',
      main: './dist/index.js',
      scripts: {
        build: 'tsc',
        start: 'node dist/index.js',
        dev: 'tsc --watch',
      },
      dependencies: {
        '@modelcontextprotocol/sdk': '^1.0.0',
        zod: '^3.22.0',
        'node-fetch': '^3.3.2',
      },
      devDependencies: {
        typescript: '^5.4.0',
        '@types/node': '^20.0.0',
      },
      engines: {
        node: '>=18.0.0',
      },
    },
    null,
    2
  );
}

export function renderTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'Node16',
        moduleResolution: 'Node16',
        outDir: './dist',
        rootDir: './src',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: true,
      },
      include: ['src'],
      exclude: ['node_modules', 'dist'],
    },
    null,
    2
  );
}

export function renderHttpClient(): string {
  return `
import fetch from "node-fetch";
import { BASE_URL } from "./config.js";

export interface ApiCallOptions {
  method: string;
  url: string;
  params?: Record<string, string>;
  headers?: Record<string, string>;
  body?: unknown;
}

export async function callApi(options: ApiCallOptions): Promise<unknown> {
  const { method, params = {}, headers = {}, body } = options;

  // Build URL with query parameters
  let url = options.url;
  const queryString = new URLSearchParams(
    Object.entries(params).filter(([, v]) => v !== undefined && v !== "")
  ).toString();
  if (queryString) url += \`?\${queryString}\`;

  const fetchOptions: Parameters<typeof fetch>[1] = {
    method,
    headers,
  };

  if (body !== undefined && method !== "GET" && method !== "HEAD") {
    fetchOptions.body = JSON.stringify(body);
  }

  const response = await fetch(url, fetchOptions);

  const contentType = response.headers.get("content-type") ?? "";
  const responseText = await response.text();

  if (!response.ok) {
    throw new Error(
      \`HTTP \${response.status} \${response.statusText}: \${responseText}\`
    );
  }

  if (contentType.includes("application/json")) {
    try {
      return JSON.parse(responseText);
    } catch {
      return responseText;
    }
  }

  return responseText;
}
`.trimStart();
}

export function renderTypes(): string {
  return `
import type { z } from "zod";

/** Contract for a single MCP tool backed by one API operation */
export interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: z.ZodObject<z.ZodRawShape>;
  execute(args: unknown): Promise<unknown>;
}
`.trimStart();
}

export function renderConfig(spec: ServiceSpec): string {
  return `
/**
 * Runtime configuration for the generated MCP server.
 *
 * Override BASE_URL via environment variable to point at a different host.
 *
 * Auth extension point:
 *   When auth is implemented, add API_KEY / BEARER_TOKEN / OAUTH_TOKEN
 *   environment variables here and inject them in each tool's header builder.
 *   The ServiceSpec.securitySchemes field carries the upstream auth metadata.
 *
 * Transport extension point:
 *   This server uses stdio. To switch to SSE or HTTP transport, replace
 *   StdioServerTransport in src/index.ts with the appropriate SDK transport.
 *   The IR TransportKind field is already plumbed for this.
 */
export const BASE_URL: string =
  process.env["MCP_BASE_URL"] ?? ${JSON.stringify(spec.baseUrl)};
`.trimStart();
}

export function renderReadme(spec: ServiceSpec, operations: number): string {
  return `
# ${spec.title} MCP Server

Auto-generated by **vis** from OpenAPI ${spec.version}.

${spec.description ? `${spec.description}\n` : ''}
## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

## Usage

\`\`\`bash
node dist/index.js
\`\`\`

The server communicates over **stdio** (MCP standard transport).

## Configuration

| Variable | Default | Purpose |
|---|---|---|
| \`MCP_BASE_URL\` | \`${spec.baseUrl}\` | Upstream API base URL |

## Tools (${operations} total)

${spec.operations
  .map(
    (op) =>
      `### \`${op.operationId}\`\n\`${op.method.toUpperCase()} ${op.path}\`${op.summary ? `\n\n${op.summary}` : ''}`
  )
  .join('\n\n')}

## Extension Points

The following capabilities are **IR-supported but not yet implemented** in the generated output:

- **Authentication**: \`ServiceSpec.securitySchemes\` carries upstream auth metadata. Inject headers in \`src/http-client.ts\` and \`MCP_API_KEY\` / \`MCP_BEARER_TOKEN\` env vars in \`src/config.ts\`.
- **SSE transport**: Replace \`StdioServerTransport\` with the SDK's SSE transport. The \`TransportKind\` field in the IR already models this.
- **HTTP transport**: Same swap point as SSE; the IR \`transport\` field is \`"http"\`-ready.
`.trimStart();
}
